### ISSUE TITLE
Unable to turn on thread on hex screw

### ISSUE THREAD

**Issue by krezac** [shaise/FreeCAD_FastenersWB#166]
Click:
- Add ISO 4017 Hex Head Screw
- select it
- switch thread to true
- click some other field

```
00:01:38  Traceback (most recent call last):
  File "C:\Users\krezac\AppData\Roaming\FreeCAD\Mod\fasteners\.\FastenersCmd.py", line 448, in execute
    s = screwMaker.createFastener(self)
  File "C:\Users\krezac\AppData\Roaming\FreeCAD\Mod\fasteners\.\ScrewMaker.py", line 418, in createFastener
    return self.createScrew(screwTables[fastenerAttribs.type][FUNCTION_POS], fastenerAttribs)
  File "C:\Users\krezac\AppData\Roaming\FreeCAD\Mod\fasteners\.\screw_maker.py", line 170, in createScrew
    screw = eval(function)
  File "<string>", line 1, in <module>
  File "C:\Users\krezac\AppData\Roaming\FreeCAD\Mod\fasteners\.\FsFunctions\FSmakeHexHeadBolt.py", line 95, in makeHexHeadBolt
    head = self.RevolveZ(aFace.revolve)
  File "C:\Users\krezac\AppData\Roaming\FreeCAD\Mod\fasteners\.\screw_maker.py", line 344, in RevolveZ
    return profile.revolve(Base.Vector(0, 0, 0), Base.Vector(0, 0, 1), angle)
<class 'AttributeError'>: 'builtin_function_or_method' object has no attribute 'revolve'
00:01:38  Recompute failed! Please check report view.
```

In

```
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.29177 (Git)
Build type: Release
Branch: releases/FreeCAD-0-20
Hash: 68e337670e227889217652ddac593c93b5e8dc94
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.2
Locale: Czech/Czech Republic (cs_CZ)
Installed mods: 
  * Curves 0.5.6
  * fasteners 0.4.3
  * fcgear 1.0.0
```

**Comment by shaise** [comment]
Hi, thanks for the catch!
It should be fixed now, please update and check.
