### ISSUE TITLE
Error creating thread in M5 nut

### ISSUE THREAD

**Issue by TreidenX** [shaise/FreeCAD_FastenersWB#42]
OS: Windows 10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.17.13541 (Git)
Build type: Release
Branch: releases/FreeCAD-0-17
Hash: 9948ee4f1570df9216862a79705afb367b2c6ffb
Python version: 2.7.14
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.2.0

Error creating thread in M5 nut (ISO-4032, ISO-4033, ISO-4035):

Traceback (most recent call last):
  File "C:\Users\atnwe\AppData\Roaming\FreeCAD\Mod\fasteners\FastenersCmd.py", line 121, in execute
    s = screwMaker.createFastener(fp.type, d, l, threadType, True)
  File "C:\Users\atnwe\AppData\Roaming\FreeCAD\Mod\fasteners\ScrewMaker.py", line 264, in createFastener
    return self.createScrew(type, diam, len, threadType, shapeOnly)
  File "C:\Users\atnwe\AppData\Roaming\FreeCAD\Mod\fasteners\screw_maker.py", line 2230, in createScrew
    screw = self.makeIso4032(ST_text, ND_text)
  File "C:\Users\atnwe\AppData\Roaming\FreeCAD\Mod\fasteners\screw_maker.py", line 4655, in makeIso4032
    nutShell = Part.Shell(nutFaces)
<class 'Part.OCCError'>: Shape is not a shell

Error creating thread in M5 nut (EN-1661):

Traceback (most recent call last):
  File "C:\Users\atnwe\AppData\Roaming\FreeCAD\Mod\fasteners\FastenersCmd.py", line 121, in execute
    s = screwMaker.createFastener(fp.type, d, l, threadType, True)
  File "C:\Users\atnwe\AppData\Roaming\FreeCAD\Mod\fasteners\ScrewMaker.py", line 264, in createFastener
    return self.createScrew(type, diam, len, threadType, shapeOnly)
  File "C:\Users\atnwe\AppData\Roaming\FreeCAD\Mod\fasteners\screw_maker.py", line 2234, in createScrew
    screw = self.makeEN1661(ND_text)
  File "C:\Users\atnwe\AppData\Roaming\FreeCAD\Mod\fasteners\screw_maker.py", line 4825, in makeEN1661
    headShell = Part.Shell(topFaces)
<class 'Part.OCCError'>: Shape is not a shell

At a choice DIN-557, DIN-562, DIN-985 the thread is not created with any size and without errors.

**Comment by shaise** [comment]
Yes, I have noticed for sometime. I notified the developer and will implement the fix as soon as he solves it.

**Comment by pubpsv** [comment]
Error creating thread in nut M30

**Comment by gabirx** [comment]
Error creating thread in nut (M27) - shape is not a shell
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\FreeCAD\Mod\fasteners\FastenersCmd.py", line 121, in execute
    s = screwMaker.createFastener(fp.type, d, l, threadType, True)
  File "C:\Users\user\AppData\Roaming\FreeCAD\Mod\fasteners\ScrewMaker.py", line 264, in createFastener
    return self.createScrew(type, diam, len, threadType, shapeOnly)
  File "C:\Users\alexandr\AppData\Roaming\FreeCAD\Mod\fasteners\screw_maker.py", line 2230, in createScrew
    screw = self.makeIso4032(ST_text, ND_text)
  File "C:\Users\user\AppData\Roaming\FreeCAD\Mod\fasteners\screw_maker.py", line 4655, in makeIso4032
    nutShell = Part.Shell(nutFaces)
<class 'Part.OCCError'>: Shape is not a shell

**Comment by luzpaz** [comment]
@shaise any progress?

**Comment by shaise** [comment]
@luzpaz This is Ulrich's code. I think it got something to do with OCC.

**Comment by luzpaz** [comment]
@shaise can we ping ulrich on this, just so if there needs to be a workaround or an upstream OCC ticket made ?

**Comment by shaise** [comment]
We can ping him, I just dont know how.

**Comment by easyw** [comment]
@shaise ... I think this is his repo
https://github.com/ulrich1a
than to ping him you can just put @ulrich1a here.
PS @shaise would you please have a look at this [PR 79 @ SheetMetal](https://github.com/shaise/FreeCAD_SheetMetal/pull/79)?

**Comment by shaise** [comment]
@easyw, regarding 79, I'm more or less OK with it, But I'm waiting for your approval.

**Comment by easyw** [comment]
@shaise I think we can merge it and then apply the fix to drop to old method in case of simple models.
I have also a new pr pending, for improving some unfolding user case as seen at freecad forum.

**Comment by luzpaz** [comment]
status on this ?

**Comment by luzpaz** [comment]
> status on this ?  

bump

**Comment by shaise** [comment]
Still waiting for @ulrich1a to investigate. Don't actually know why the new OCC complains on the thread generation, and also why it only happens for certain M sizes and not others.

**Comment by Altair31** [comment]
@ulrich1a did not make a single commit in a year. Do you have any contact ?

**Comment by shaise** [comment]
nope!

**Comment by ulrich1a** [comment]
I am still alive. I have to admit, that I my focus had moved to other things for a long time. I have been working the last days on the issue with the nuts and found a solution. It is a little bit faster but needs still some tuning. I will upload the current status to my github account.

**Comment by shaise** [comment]
great! good to hear from you!

**Comment by ulrich1a** [comment]
Added the new code to github: https://github.com/ulrich1a/screw_maker

**Comment by shaise** [comment]
great! I will take a look and try to merge it.

**Comment by shaise** [comment]
Should be fixed now. Thank you @ulrich1a !

**Comment by luzpaz** [comment]
@shaise FYI, if you add `closes #42` to the git summary it will automatically close this ticket.

**Comment by shaise** [comment]
Thanks for the tip. However, I think it should be closed by issue owner.

**Comment by luzpaz** [comment]
bump @TreidenX
