### ISSUE TITLE
WB is fail to start when used with FreeCad 0.18.1

### ISSUE THREAD

**Issue by elf128** [shaise/FreeCAD_FastenersWB#46]
Traceback (most recent call last):
  File "/home/vlad/.FreeCAD/Mod/fasteners/FastenersCmd.py", line 31, in <module>
    import FastenerBase
  File "/home/vlad/.FreeCAD/Mod/fasteners/FastenerBase.py", line 58, in <module>
    DropButtonSupported = int(FreeCAD.Version()[1]) > 15 # and  int(FreeCAD.Version()[2].split()[0]) >= 5165
<class 'ValueError'>: invalid literal for int() with base 10: '18.1'

Fixed locally casting FreeCAD.Version()[1] to float and then to int.

**Comment by elf128** [comment]
duplicate of #45
