### ISSUE TITLE
some screws cannot be created in FC latest (11300)

### ISSUE THREAD

**Issue by easyw** [shaise/FreeCAD_FastenersWB#7]
with some screws (i.e. DIN967, ISO7045, ISO7046, ISO7047, ISO7048)
I get the following errors:
> Traceback (most recent call last):
>   File "C:\Users\mau\AppData\Roaming\FreeCAD\Mod\fasteners\FastenersCmd.py", line 119, in execute
>     s = screwMaker.createScrew(fp.type, d, l, threadType, True)
>   File "C:\Users\mau\AppData\Roaming\FreeCAD\Mod\fasteners\screw_maker.py", line 2205, in createScrew
>     screw = self.makeIso7045(ST_text, ND_text,l)
>   File "C:\Users\mau\AppData\Roaming\FreeCAD\Mod\fasteners\screw_maker.py", line 2717, in makeIso7045
>     recess, recessShell = self.makeCross_H3(cT, mH, hcr)
>   File "C:\Users\mau\AppData\Roaming\FreeCAD\Mod\fasteners\screw_maker.py", line 5007, in makeCross_H3
>     crossFaces.append(crossShell.Faces[i])
> <type 'exceptions.IndexError'>: list index out of range

PS thx for this nice WB
Maurice

**Comment by easyw** [comment]
Thx for merging :smile:
